### ISSUE TITLE
render_data

### ISSUE THREAD

**Issue by UestcJay** [shunsukesaito/PIFu#123]
many thanks for your work! when I run render_data.py, there is a  error return.

ssh://root@172.18.41.24:7760/root/anaconda3/envs/pifu/bin/python -u /root/shenzhen/lkq/PIFu/apps/render_data.py -e
Traceback (most recent call last):
  File "/root/shenzhen/lkq/PIFu/apps/render_data.py", line 281, in <module>
    initialize_GL_context(width=args.size, height=args.size, egl=args.egl)
  File "/root/shenzhen/lkq/PIFu/lib/renderer/gl/init_gl.py", line 22, in initialize_GL_context
    create_opengl_context((width, height))
  File "/root/shenzhen/lkq/PIFu/lib/renderer/gl/glcontext.py", line 110, in create_opengl_context
    raise ImportError('Cannot initialize a headless EGL display.')
ImportError: Cannot initialize a headless EGL display.

Process finished with exit code 1

how to solve it?

**Comment by BhaumikThakkar** [comment]
Hello there, this might help:
export MESA_GL_VERSION_OVERRIDE=3.3 in terminal
Thank You

**Comment by ilhamuh97** [comment]
> Hello there, this might help: export MESA_GL_VERSION_OVERRIDE=3.3 in terminal Thank You

Hi, do you have another solution for this? it's working on my local Docker container, but it's not working on the Docker container in the server. I don't know what's the difference

**Comment by BhaumikThakkar** [comment]
> > Hello there, this might help: export MESA_GL_VERSION_OVERRIDE=3.3 in terminal Thank You
> 
> 
> 
> Hi, do you have another solution for this? it's working on my local Docker container, but it's not working on the Docker container in the server. I don't know what's the difference

Hey, I have tried on local so don't know about docker cuz I haven't executed there.

**Comment by ilhamuh97** [comment]
Install everything with conda/mamba fix the issue. It's working. Thank you
