### ISSUE TITLE
Data Generation results

### ISSUE THREAD

**Issue by cathylacus** [shunsukesaito/PIFu#27]
I can't run the second step in Data Generation (2.run the following script. Under the specified data path, the code creates folders named GEO, RENDER, MASK, PARAM, UV_RENDER, UV_MASK, UV_NORMAL, and UV_POS. Note that you may need to list validation subjects to exclude from training in {path_to_training_data}/val.txt (this tutorial has only one subject and leave it empty).If you wish to render images with headless servers equipped with NVIDIA GPU, add -e to enable EGL rendering.) 
      Can I get the results，like a zip file？

**Comment by shunsukesaito** [comment]
Can you elaborate? What are the errors? Also please provide your environment (os, GPU type etc).

**Comment by shunsukesaito** [comment]
> Can I get the results，like a zip file？
"the code creates folders named GEO, RENDER, MASK, PARAM, UV_RENDER, UV_MASK, UV_NORMAL, and UV_POS". Under each folder, image and npy files are generated, not as a zip file.

**Comment by cathylacus** [comment]
> > Can I get the results，like a zip file？
> 
> "the code creates folders named GEO, RENDER, MASK, PARAM, UV_RENDER, UV_MASK, UV_NORMAL, and UV_POS". Under each folder, image and npy files are generated, not as a zip file.

my error is “freeglut (foo): failed to open display ''”
My environment is a command Linux, a server without a graphical interface, so I can't generate training sets?

**Comment by shunsukesaito** [comment]
Does your server have NVIDIA GPU? If so, run the commend with -e option. Also make sure you update nvidia driver to use eGPU option.

**Comment by cathylacus** [comment]
> Does your server have NVIDIA GPU? If so, run the commend with -e option. Also make sure you update nvidia driver to use eGPU option.

Yes，I have NVIDIA GTX 2080ti，I try it，Thanks！

**Comment by cathylacus** [comment]
> Also make sure you update nvidia driver to use eGPU option.

How do I  make sure my nvidia driver to use eGPU option.Thanks！

**Comment by shunsukesaito** [comment]
You need to install EGL related packages by running the following command (assuming you use ubuntu) 
`apt install libgl1-mesa-dri libegl1-mesa libgbm1`
Otherwise, you don't need to switch by yourself. My code should automatically switch to eGPU and render images for you.

**Comment by cathylacus** [comment]
> You need to install EGL related packages by running the following command (assuming you use ubuntu)
> `apt install libgl1-mesa-dri libegl1-mesa libgbm1`
> Otherwise, you don't need to switch by yourself. My code should automatically switch to eGPU and render images for you.

Thanks！

**Comment by cathylacus** [comment]
> You need to install EGL related packages by running the following command (assuming you use ubuntu)
> `apt install libgl1-mesa-dri libegl1-mesa libgbm1`
> Otherwise, you don't need to switch by yourself. My code should automatically switch to eGPU and render images for you.

Now，New error is “OpenGL.raw.EGL._errors.EGLError: EGLError”

**Comment by cathylacus** [comment]
> You need to install EGL related packages by running the following command (assuming you use ubuntu)
> `apt install libgl1-mesa-dri libegl1-mesa libgbm1`
> Otherwise, you don't need to switch by yourself. My code should automatically switch to eGPU and render images for you.

error:
Traceback (most recent call last):
  File "/root/anaconda3/envs/PIFu/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/PIFu/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/test/liwei/PIFu-master/PIFu-master/apps/render_data.py", line 282, in <module>
    initialize_GL_context(width=args.size, height=args.size, egl=args.egl)
  File "/test/liwei/PIFu-master/PIFu-master/lib/renderer/gl/init_gl.py", line 23, in initialize_GL_context
    create_opengl_context((width, height))
  File "/test/liwei/PIFu-master/PIFu-master/lib/renderer/gl/glcontext.py", line 91, in create_opengl_context
    egl.eglInitialize(egl_display, pointer(major), pointer(minor))
  File "/root/anaconda3/envs/PIFu/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError
OpenGL.raw.EGL._errors.EGLError: EGLError(
	err = EGL_NOT_INITIALIZED,
	baseOperation = eglInitialize,
	cArguments = (
		<OpenGL._opaque.EGLDisplay_pointer object at 0x7efff1427598>,
		<OpenGL.raw.EGL._types.LP_c_int object at 0x7effef42e620>,
		<OpenGL.raw.EGL._types.LP_c_int object at 0x7effef42e510>,
	),
	result = 0
)

**Comment by shunsukesaito** [comment]
Can you run the example in the following repository without any issue? If not, you may as well get help from egl community.
https://github.com/eduble/gl

**Comment by cathylacus** [comment]
> Can you run the example in the following repository without any issue? If not, you may as well get help from egl community.
> https://github.com/eduble/gl

I found my NVIDIA driver is 435.21，and “Warning: I found that outdated NVIDIA drivers may cause errors with EGL. If you want to try out the EGL version, please update your NVIDIA driver to the latest!!”，so is my driver not new enough?

**Comment by shunsukesaito** [comment]
Probably your driver is new enough. Can you run nvidia-smi from the command line and see this driver version? If you use VM, GPUs might not be visible from client side. 
Also did you get the same error when you run the code in the repository above?

**Comment by cathylacus** [comment]
> Probably your driver is new enough. Can you run nvidia-smi from the command line and see this driver version? If you use VM, GPUs might not be visible from client side.
> Also did you get the same error when you run the code in the repository above?

I can use nvidia-smi and see this driver version，I run the egl  example，and the error is：
![1](https://user-images.githubusercontent.com/63350070/83352134-17df3e00-a37c-11ea-89e7-02d3dd55876b.png)

**Comment by cathylacus** [comment]
> Probably your driver is new enough. Can you run nvidia-smi from the command line and see this driver version? If you use VM, GPUs might not be visible from client side.
> Also did you get the same error when you run the code in the repository above?

I run the generate folders is also the error.o(╥﹏╥)o

**Comment by wangfudong** [comment]
> my error is “freeglut (foo): failed to open display ''”
> My environment is a command Linux, a server without a graphical interface, so I can't generate training sets?

You have a server without a graphical interface, so I guess you can not directly run the second script of data generation.  You can, 1) use a server with graphical interface; 2) rewrite the data generation code such that it runs without graphics display; 3) if your server suports or is allowed to use SSH X11 Forwarding, you can modify the SSH settings and use some tools like MobaxTerm to run the data-generation code.

**Comment by cathylacus** [comment]
> > my error is “freeglut (foo): failed to open display ''”
> > My environment is a command Linux, a server without a graphical interface, so I can't generate training sets?
> 
> You have a server without a graphical interface, so I guess you can not directly run the second script of data generation. You can, 1) use a server with graphical interface; 2) rewrite the data generation code such that it runs without graphics display; 3) if your server suports or is allowed to use SSH X11 Forwarding, you can modify the SSH settings and use some tools like MobaxTerm to run the data-generation code.

Thank for your reporting!

**Comment by adelekuzmiakova** [comment]
> my error is “freeglut (foo): failed to open display ''”
> My environment is a command Linux, a server without a graphical interface, so I can't generate training sets?

Hi @cathylacus, 

I'm just curious as to whether you were able to get the `apps.render_data.py` code running on your Linux server? I was running the same code on an AWS Linux instance which also does not have a graphical interface. Make sure you use `-e` argument:

```bash
python -m apps.render_data -i [path-to-obj-file] -o [dir-to-save] -e
```
Otherwise you can enable X11 forwarding from you Linux server; here's [an example](https://aws.amazon.com/blogs/compute/how-to-enable-x11-forwarding-from-red-hat-enterprise-linux-rhel-amazon-linux-suse-linux-ubuntu-server-to-support-gui-based-installations-from-amazon-ec2/) on how to do it. Hope this helps :)

**Comment by cathylacus** [comment]
> > my error is “freeglut (foo): failed to open display ''”
> > My environment is a command Linux, a server without a graphical interface, so I can't generate training sets?
> 
> Hi @cathylacus,
> 
> I'm just curious as to whether you were able to get the `apps.render_data.py` code running on your Linux server? I was running the same code on an AWS Linux instance which also does not have a graphical interface. Make sure you use `-e` argument:
> 
> ```shell
> python -m apps.render_data -i [path-to-obj-file] -o [dir-to-save] -e
> ```
> 
> Otherwise you can enable X11 forwarding from you Linux server; here's [an example](https://aws.amazon.com/blogs/compute/how-to-enable-x11-forwarding-from-red-hat-enterprise-linux-rhel-amazon-linux-suse-linux-ubuntu-server-to-support-gui-based-installations-from-amazon-ec2/) on how to do it. Hope this helps :)

Sorry,I already gave up this code.

**Comment by cathylacus** [comment]
> > my error is “freeglut (foo): failed to open display ''”
> > My environment is a command Linux, a server without a graphical interface, so I can't generate training sets?
> 
> Hi @cathylacus,
> 
> I'm just curious as to whether you were able to get the `apps.render_data.py` code running on your Linux server? I was running the same code on an AWS Linux instance which also does not have a graphical interface. Make sure you use `-e` argument:
> 
> ```shell
> python -m apps.render_data -i [path-to-obj-file] -o [dir-to-save] -e
> ```
> 
> Otherwise you can enable X11 forwarding from you Linux server; here's [an example](https://aws.amazon.com/blogs/compute/how-to-enable-x11-forwarding-from-red-hat-enterprise-linux-rhel-amazon-linux-suse-linux-ubuntu-server-to-support-gui-based-installations-from-amazon-ec2/) on how to do it. Hope this helps :)

You should try the code on  an AWS Linux,I just have Command interface,So I give up the code.

**Comment by LazerLikeFocus** [comment]
I am facing a similar issue on Colab after running render_data.py.
Any solution ?

After installing conda on colab and installing all req libs on colab, I was able to run the prt_util.py.
But not render_data.py.

Here is the error : 
Traceback (most recent call last):
  File "/content/PIFu/apps/render_data.py", line 293, in <module>
    initialize_GL_context(width=args.size, height=args.size, egl=args.egl)
  File "/usr/local/lib/python3.6/site-packages/lib/renderer/gl/init_gl.py", line 22, in initialize_GL_context
    create_opengl_context((width, height))
  File "/usr/local/lib/python3.6/site-packages/lib/renderer/gl/glcontext.py", line 110, in create_opengl_context
    raise ImportError('Cannot initialize a headless EGL display.')
ImportError: Cannot initialize a headless EGL display.

**Comment by Uuiiii** [comment]
` python -m apps.prt_util -i {path_to_rp_dennis_posed_004_OBJ}`
When I run this code, I get the following error:
![1646787121(1)](https://user-images.githubusercontent.com/95684907/157351233-4c6cadd7-82eb-4f36-a188-e71751ada3ea.png)
@shunsukesaito

**Comment by Yuhuoo** [comment]
> egl community

I also want to know the answer fixing the bug

**Comment by BhaumikThakkar** [comment]
> > You need to install EGL related packages by running the following command (assuming you use ubuntu)
> > `apt install libgl1-mesa-dri libegl1-mesa libgbm1`
> > Otherwise, you don't need to switch by yourself. My code should automatically switch to eGPU and render images for you.
> 
> error: Traceback (most recent call last): File "/root/anaconda3/envs/PIFu/lib/python3.6/runpy.py", line 193, in _run_module_as_main "**main**", mod_spec) File "/root/anaconda3/envs/PIFu/lib/python3.6/runpy.py", line 85, in _run_code exec(code, run_globals) File "/test/liwei/PIFu-master/PIFu-master/apps/render_data.py", line 282, in initialize_GL_context(width=args.size, height=args.size, egl=args.egl) File "/test/liwei/PIFu-master/PIFu-master/lib/renderer/gl/init_gl.py", line 23, in initialize_GL_context create_opengl_context((width, height)) File "/test/liwei/PIFu-master/PIFu-master/lib/renderer/gl/glcontext.py", line 91, in create_opengl_context egl.eglInitialize(egl_display, pointer(major), pointer(minor)) File "/root/anaconda3/envs/PIFu/lib/python3.6/site-packages/OpenGL/platform/baseplatform.py", line 415, in **call** return self( *args, **named ) File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError OpenGL.raw.EGL._errors.EGLError: EGLError( err = EGL_NOT_INITIALIZED, baseOperation = eglInitialize, cArguments = ( <OpenGL._opaque.EGLDisplay_pointer object at 0x7efff1427598>, <OpenGL.raw.EGL._types.LP_c_int object at 0x7effef42e620>, <OpenGL.raw.EGL._types.LP_c_int object at 0x7effef42e510>, ), result = 0 )

export MESA_GL_VERSION_OVERRIDE=3.3
