### ISSUE TITLE
vertex shader lacks `main'\n"

### ISSUE THREAD

**Issue by AstitvaSri** [shunsukesaito/PIFu#48]
Hey,
While generating the data using render_data.py with OpenGL 3.1.5 (as recommended), the following error was encountered:

Linker failure: 
b"error: vertex shader lacks ``main'\n"`
3
Traceback (most recent call last):
  File "/home/iiit/anaconda3/envs/ENV_PIFU_TRAIN/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/iiit/anaconda3/envs/ENV_PIFU_TRAIN/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/iiit/PIFu_Training/PIFu-master/apps/render_data.py", line 290, in <module>
    rndr = PRTRender(width=args.size, height=args.size, ms_rate=args.ms_rate, egl=args.egl)
  File "/home/iiit/PIFu_Training/PIFu-master/lib/renderer/gl/prt_render.py", line 10, in __init__
    CamRender.__init__(self, width, height, name, program_files=program_files, color_size=8, ms_rate=ms_rate, egl=egl)
  File "/home/iiit/PIFu_Training/PIFu-master/lib/renderer/gl/cam_render.py", line 8, in __init__
    Render.__init__(self, width, height, name, program_files, color_size, ms_rate=ms_rate, egl=egl)
  File "/home/iiit/PIFu_Training/PIFu-master/lib/renderer/gl/render.py", line 42, in __init__
    self.model_mat_unif = glGetUniformLocation(self.program, 'ModelMat')
  File "/home/iiit/anaconda3/envs/ENV_PIFU_TRAIN/lib/python3.7/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/home/iiit/anaconda3/envs/ENV_PIFU_TRAIN/lib/python3.7/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
  File "/home/iiit/anaconda3/envs/ENV_PIFU_TRAIN/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "/home/iiit/anaconda3/envs/ENV_PIFU_TRAIN/lib/python3.7/site-packages/OpenGL/error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetUniformLocation,
	cArguments = (3, b'ModelMat\x00'),
	result = -1
)

I've tried various versions of OpenGL but the issue is still remaining? Can you look into this.

**Comment by shunsukesaito** [comment]
Can you provide necessary information (e.g., OS, environment) to reproduce the issue?
